AnnualReport/AdminApp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'adminApp'
urlpatterns = [
    path('/', include([
        path('adminHome', views.adminHome, name='adminHome'),
        path('generateReport', views.generateReport, name="generateReport"),
        path('generateReportResult/<str:fromYear>/<str:toYear>', views.generateReportResult, name="generateReportResult"),
        path('GeneratePdf/<str:fromYear>/<str:toYear>', views.GeneratePdf, name='GeneratePdf')
    ])),

]

AnnualReport/AnnualReport/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.home, name="Home"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('logout', views.logout, name="logout"),
    path('adminApp', include('AdminApp.urls')),
    path('CSE', include('CSE.urls')),
    path('IT', include('IT.urls')),
    path('Civil', include('Civil.urls')),
    path('ME', include('ME.urls')),
    path('Electrical', include('Electrical.urls')),
    path('Electronics', include('Electronics.urls')),
    path('admin/', admin.site.urls),
]

AnnualReport/IT/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'IT'
urlpatterns = [
    path('/', include([
        path('teacherHome', views.teacherHome, name='teacherHome'),
        path('teacherProfile', views.teacherProfile, name='teacherProfile'),
        path('editTeacherProfile', views.editTeacherProfile, name='editTeacherProfile'),
        path('changePassword', views.changePassword, name="changePassword"),
        path('researchPapers', views.researchPapers, name='researchPapers'),
        path('addResearchPapers', views.addResearchPapers, name="addResearchPapers"),
        path('researchPaperDelete/<str:doi>', views.researchPaperDelete, name="researchPaperDelete"),
        path('phdDetails', views.phdDetails, name="phdDetails"),
        path('addPHD', views.addPHD, name="addPHD"),
        path('phdDetailsDelete/<str:id>', views.phdDetailsDelete, name="phdDetailsDelete"),
        path('studentData', views.studentData, name="studentData"),
        path('addStudentData', views.addStudentData, name="addStudentData"),
        path('importStudentData', views.importStudentData, name="importStudentData"),
        path('studentDataDelete/<str:PRN>', views.studentDataDelete, name="studentDataDelete"),
        path('bookPublished', views.bookPublished, name="bookPublished"),
        path('addBookPublished', views.addBookPublished, name="addBookPublished"),
        path('bookPublishedDelete/<str:id>', views.bookPublishedDelete, name="bookPublishedDelete"),
        path('patents', views.patents, name="patents"),
        path('addPatents', views.addPatents, name="addPatents"),
        path('patentsDelete/<str:id>', views.patentsDelete, name="patentsDelete"),
        path('facultyCompletedCourse', views.facultyCompletedCourse, name="facultyCompletedCourse"),
        path('addFacultyCompletedCourse', views.addFacultyCompletedCourse, name="addFacultyCompletedCourse"),
        path('facultyCompletedCourseDelete/<str:id>', views.facultyCompletedCourseDelete, name="facultyCompletedCourseDelete"),
        path('guidePhdDetails', views.guidePhdDetails, name="guidePhdDetails"),
        path('addGuidePHD', views.guideAddPHD, name="addGuidePHD"),
        path('guidePhdDetailsDelete/<str:id>', views.guidePhdDetailsDelete, name="guidePhdDetailsDelete"),
        path('googleScholarCitationDetails', views.googleScholarCitationDetails, name="googleScholarCitationDetails"),
        path('addGoogleScholarCitationDetails', views.addGoogleScholarCitationDetails, name="addGoogleScholarCitationDetails"),
        path('googleScholarCitationDetailsDelete/<str:id>', views.googleScholarCitationDetailsDelete, name="googleScholarCitationDetailsDelete"),
        path('guestLecOrganizedOrDelivered', views.guestLecOrganizedOrDelivered, name="guestLecOrganizedOrDelivered"),
        path('addguestLecOrganizedOrDelivered', views.addguestLecOrganizedOrDelivered, name="addguestLecOrganizedOrDelivered"),
        path('guestLecOrganizedOrDeliveredDelete/<str:id>', views.guestLecOrganizedOrDeliveredDelete, name="guestLecOrganizedOrDeliveredDelete"),
        path('eventConductedOrAttended', views.eventConductedOrAttended, name="eventConductedOrAttended"),
        path('addeventConductedOrAttended', views.addeventConductedOrAttended, name="addeventConductedOrAttended"),
        path('eventConductedOrAttendedDelete/<str:id>', views.eventConductedOrAttendedDelete, name="eventConductedOrAttendedDelete"),
    ])),

]

AnnualReport/templates/addBookPublished.html
{% extends 'base.html' %}

{% block title %}
    Add Published Books
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Published Books</h1>
    <br>

    <form class="form-horizontal"  role="form" action="addBookPublished" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="name_faculty">
                Faculty Name:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="name_faculty" type="text" name="name_faculty" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="title_of_book">
                Title of Book:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="title_of_book" type="text" name="title_of_book" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="name_of_publisher">
                Name of Publisher:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="name_of_publisher" type="text" name="name_of_publisher" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="date_publication">
                Publication Date:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="startDate" type="date" name="date_publication" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReport/templates/addFacultyCompletedCourse.html
{% extends 'base.html' %}

{% block title %}
    Add Faculty Completed Course
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Faculty Completed Course</h1>
    <br>

    <form class="form-horizontal"  role="form" action="addFacultyCompletedCourse" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="faculty_name">
                Faculty Name:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="faculty_name" type="text" name="faculty_name" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="title_course">
                Title of Course:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="title_course" type="text" name="title_course" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="startDate">
                Starting Date:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="startDate" type="date" name="starting_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="endDate">
                Completion Date:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="endDate" type="date" name="completion_date" required>
            </div>
        </div>
        <div class="form-group">
            <label class="control-label col-sm-2" for="mode">
                Mode:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="mode" type="text" name="mode" required>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReport/templates/addguestLecOrganizedOrDelivered.html
{% extends 'base.html' %}

{% block title %}
    Add Guest Lecture Organized or Delivered Details
{% endblock %}

{% load static %}

{% block content %}
    <h1>Add Guest Lecture Organized and Delivered Details</h1>
    <br>
    <form class="form-horizontal"  role="form" action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label class="control-label col-sm-2" for="teacher_name">
                Teacher Name:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="teacher_name" type="text" name="teacher_name" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="subject">
                Subject:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="subject" type="text" name="subject" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="place">
                Place:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="place" type="text" name="place" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="startDate" >
                Starting Date:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="startDate" type="date" name="starting_date" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="endDing_date" >
                Ending Date:
            </label>
            <div class="col-sm-10">
                <input class="form-control" id="endDate" type="date" name="ending_date" required>
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-sm-2" for="type">
                Type of Lecture:
            </label>
            <div class="col-sm-10">
                <select class="form-select" id="type" name="type" required>
                    <option value="Organized">Organized</option>
                    <option value="Delivered">Delivered</option>
                </select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-3">
                <label class="control-label" for="ddlYears">
                    Academic Year:
                </label>
                <select name="academic_year" id="ddlYears"></select>
                -
                <select name="toYear" id="ddlYears2"></select>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-10">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </form>
    <br>

    <script src="{% static '/js/DateValidation.js' %}"></script>
    <script src="{% static '/js/year.js' %}"></script>
    <script src="{% static '/js/year2.js' %}"></script>
{% endblock %}

AnnualReport/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
        {% endblock %}

    </title>

    {#    Bootstrap CSS#}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/footerStyle.css' %}">
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

    <span class="navbar-brand mb-0 h1">WCE</span>

    <div class="collapse navbar-collapse" id="navbarNav">

        <ul class="navbar-nav ml-auto">

            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link">Hello, {{user.first_name}}</a>
                </li>
                {% if isAdmin %}

                <li class="nav-item">
                    <a class="nav-link" href="/adminApp/adminHome">Home</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'adminApp:generateReport' %}">Generate Report</a>
                </li>
                
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

                {% else %}

                    <li class="nav-item">
                        <a class="nav-link" href="teacherHome">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="teacherProfile">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% endif %}

            {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}

    {% endblock %}
</div>

<!-- Footer -->
<footer id="footer">
    <!-- Footer Links -->
    <div class="container text-center text-md-left">
        <!-- Grid row -->
        <div class="row">
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mr-auto my-md-4 my-0 mt-4 mb-1">
                <!-- Content -->
                <h5 class="font-weight-bold text-uppercase mb-4">Address</h5>
                <p>Walchand College of Engineering,<br>
                    A/P: Vishrambagh,<br>
                    Sangli - 416 415<br>
                    Maharashtra, India<br>
                    Tel: +91-233-2300383<br>
                    Fax: +91-233-2300831<br>
                    <a href="mailto:kiran.raut@walchandsangli.ac.in">Contact Us</a>
                </p>
            </div>
            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 mx-auto my-md-4 my-0 mt-4 mb-1">
                <!-- Links -->
                <h5 class="font-weight-bold text-uppercase mb-4">About</h5>
                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="http://www.walchandsangli.ac.in">About WCE Sangli</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="http://112.133.242.241/moodle/">WCE Moodle</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="https://alumni.walchandsangli.ac.in/">Alumni Portal</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="https://walchandsangli.edugrievance.com/">Grievance Portal</a>
                        </p>
                    </li>
                </ul>

            </div>
            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-md-4 col-lg-3 mx-auto my-md-4 my-0 mt-4 mb-1">
                <!-- Contact details -->
                <h5 class="font-weight-bold text-uppercase mb-4">External Links</h5>
                <ul class="list-unstyled">
                    <li>
                        <p>
                            <a href="https://www.aicte-india.org/">AICTE</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="https://www.ugc.ac.in/">UGC</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="https://www.nbaind.org/">NBA</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="http://www.dtemaharashtra.gov.in/index.html">DTE</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="http://www.unishivaji.ac.in/">Shivaji University</a>
                        </p>
                    </li>
                    <li>
                        <p>
                            <a href="https://www.nirfindia.org/Home">NIRF</a>
                        </p>
                    </li>
                </ul>
            </div>
            <!-- Grid column -->
            <hr class="clearfix w-100 d-md-none">
            <!-- Grid column -->
            <div class="col-md-2 col-lg-2 text-center mx-auto my-4">
                <!-- Social buttons -->
                <h5 class="font-weight-bold text-uppercase mb-4">Follow Us</h5>
                <!-- Facebook -->
                <a href="" type="button" class="btn-floating btn-fb">
                    <i class="fa fa-facebook-f"></i>
                </a>
                <!-- Twitter -->
                <a href="" type="button" class="btn-floating btn-tw">
                    <p><i class="fa fa-twitter"></i></p>
                </a>
                <!-- Google +-->
                <a href="" type="button" class="btn-floating btn-gplus">
                    <p><i class="fa fa-google-plus-g"></i></p>
                </a>
                <!-- Dribbble -->
                <a href="" type="button" class="btn-floating btn-dribbble">
                    <p><i class="fa fa-dribbble"></i></p>
                </a>
            </div>
            <!-- Grid column -->
        </div>
        <!-- Grid row -->
    </div>
    <!-- Footer Links -->
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

AnnualReport/templates/bookPublished.html
{% extends 'base.html' %}

{% block title %}
    Published Books
{% endblock %}

{% block content %}

    <h1>Published Books</h1>
    <br>
    <br>
    <a class="btn btn-info" href="addBookPublished" role="button">Add Book Published</a>
    <br><br><br>
    {% for i in allPublishedBooks %}
        <div class="card text-center" style="width: 60%; margin: auto">
            <div class="card-header">
                Title of Book:  {{ i.title_of_book }}
            </div>
            <div class="card-body">
                <p class="card-title">Faculty Name: {{ i.name_faculty }}</p>
                <p class="card-title">Name of Publisher: {{ i.name_of_publisher }}</p>
                <p class="card-title">Publication Date: {{ i.date_publication }}</p>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#popUpModal{{ i.id }}">
                    Delete
                </button>
            </div>
        </div>

        <!-- Modal -->
        <div class="modal fade" id="popUpModal{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="popUpModalTitle" aria-hidden="true">
            <div class=" modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="popUpModalTitle">Delete Confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h6>Are you sure, you want to delete.</h6>
                    </div>
                    <div class="modal-footer">
                        <a href="bookPublished"><button type="button" class="btn btn-secondary" >No, thanks</button></a>
                        <a href="bookPublishedDelete/{{i.id}}"><button type="button" class="btn btn-danger" >Delete</button></a>
                    </div>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}

{% endblock %}

AnnualReport/templates/changePassword.html
{% extends 'base.html' %}

{% block title %}Change Password{% endblock %}

{% block content %}
    {% if error_message %}
        <script>alert("{{ error_message }}")</script>
    {% endif %}
    <br><br>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-l-50 p-r-50 p-t-77 p-b-30">
                <form class="login100-form validate-form" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <h3 class="login100-form-title p-b-55">
                        Change Password
                    </h3>
                    <div class="col-sm-5 wrap-input100 validate-input m-b-16" data-validate = "Enter current password">
                        <input class="form-control input100" type="password" name="currentPassword" placeholder="Current password" required>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
							<span class="lnr lnr-lock"></span>
						</span>
                    </div>
                    <br>
                    <div class="col-sm-5 wrap-input100 validate-input m-b-16" data-validate = "Enter new password">
                        <input class="form-control input100" type="password" name="newPassword" placeholder="New password" required>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
							<span class="lnr lnr-lock"></span>
						</span>
                    </div>
                    <br>

                    <div class="col-sm-5" data-validate = "Re-enter new password">
                        <input class="input100 form-control" type="password" name="confirmPassword" placeholder="Confirm New Password" required>
                        <span class="focus-input100"></span>
                        <span class="symbol-input100">
                            <span class="lnr lnr-lock"></span>
						</span>
                    </div>
                    <br>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button class="btn btn-success" type="submit">
                                Save Changes
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


{%endblock%}

AnnualReport/templates/googleScholarCitationDetails.html
{% extends 'base.html' %}

{% block title %}
    Google Scholar Citation Detail
{% endblock %}

{% load static %}

{% block content %}
    <h1>Google Scholar Citation Detail</h1>
    <br>
    <a class="btn btn-info" href="addGoogleScholarCitationDetails" role="button">Add Teacher Google Citation Detail</a>
    <br><br><br>
    {% for i in googleAllCitationDetails %}
        <div class="card text-center" style="width: 60%; margin: auto">
            <div class="card-header">
                Citation Details:   {{ i.academic_year }}
            </div>
            <div class="card-body">
                <p class="card-title">Teacher Name: {{ i.teacher_name }}</p>
                <p class="card-title">Designation: {{ i.designation }}</p>
                <p class="card-title">Citations 2015: {{ i.citations_2015 }}</p>
                <p class="card-title">h-index 2015: {{ i.h_index_2015 }}</p>
                <p class="card-title">i-10 in 2015: {{ i.i_10_2015 }}</p>
                <p class="card-title">Citations All: {{ i.citations_all }}</p>
                <p class="card-title">h-index All: {{ i.h_index_all }}</p>
                <p class="card-title">i-10 All: {{ i.i_10_all }}</p>
                <p class="card-title">Cited Publication: {{ i.cited_publication }}</p>
                <p class="card-title">Reported Publication: {{ i.reported_publication }}</p>
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#popUpModal{{ i.id }}">
                    Delete
                </button>
            </div>

        </div>
        <!-- Modal -->
        <div class="modal fade" id="popUpModal{{ i.id }}" tabindex="-1" role="dialog" aria-labelledby="popUpModalTitle" aria-hidden="true">
            <div class=" modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="popUpModalTitle">Delete Confirmation</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h6>Are you sure, you want to delete.</h6>
                    </div>
                    <div class="modal-footer">
                        <a href="googleScholarCitationDetails"><button type="button" class="btn btn-secondary" >No, thanks</button></a>
                        <a href="googleScholarCitationDetailsDelete/{{i.id}}"><button type="button" class="btn btn-danger" >Delete</button></a>
                    </div>
                </div>
            </div>
        </div>
        <br>

    {% endfor %}
{% endblock %}

AnnualReport/templates/home.html
{% extends 'base.html' %}
{% block title %}WCE Home{% endblock %}

{% block content %}
    <img style="display: inline;" src="http://www.walchandsangli.ac.in/images/Walchand_11.gif" alt="logo" />
    <h1 style="display: inline;">Walchand College of Engineering, Sangli</h1><br>
    <h1 style="display: inline;">Home Page</h1>
    <br>
{% endblock %}

AnnualReport/templates/login.html
{% extends 'base.html' %}
{% block title %}
    Login
{% endblock %}

{% block content %}
    <div class="card mx-auto" style="width: 18rem;">
        <div class="card-body">
            <h3 class="card-title">Log In</h3>
            <form class="form-horizontal" action="login" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label col-sm-6">
                        Username:
                    </label>
                    <div class="col-sm-10">
                        <input maxlength="50" name="username" type="text" class="form-control" required>
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-6">
                        Password:
                    </label>
                    <div class="col-sm-10">
                        <input maxlength="30" name="password" type="password" class="form-control" required>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-success">Login</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    {% for message in messages %}
        <script>alert("{{ message }}")</script>
    {% endfor %}
{% endblock %}